import com.sample.demo.Product;
import java.util.Map;

rule "Discount Based on Product"
	when
		$product: Product(type == "desktop")
	then
	    System.out.println("Discount provided for product");
		$product.setDiscount(15);
	end


rule "Discount Based on Store A,B,C"
	when 
		$product: Product($regions : regions)
		$region: Map() from $regions
		$entry: Map.Entry( $key: key, $val: value ) from $region.entrySet()
		eval($val.equals("A") || $val.equals("B") || $val.equals("C"))
	then
	    System.out.println("Discount provided for product in specific region");
		$product.setDiscount(10);
	end

rule "Discount Based Manufacturer"
	when
		$product: Product($manufacturers : manufacturers)
		$manufacturer: String() from $manufacturers
		eval($manufacturer.equals("Company1") || $manufacturer.equals("Company2"))
	then
	    System.out.println("Discount provided for manufacturer");
		$product.setDiscount(5);
	end